apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "maptiler-server.fullname" . }}
  labels:
    {{- include "maptiler-server.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ if .Values.maptilerServer.withAdmin }} {{ sub .Values.replicaCount 1 }} {{ else }} {{ .Values.replicaCount }} {{ end }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "maptiler-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "maptiler-server.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: [
            "--adminPassword=$(MAPTILER_SERVER_ADMIN_PASSWORD)",
            "--port=$(MAPTILER_SERVER_PORT)",
            "--rasterization=$(MAPTILER_SERVER_RASTERIZATION)",
            "--withAdmin=$(MAPTILER_SERVER_WITH_ADMIN)",
            "--workDir=$(MAPTILER_SERVER_WORK_DIR)"
          ]
          ports:
            - name: http
              containerPort: {{ .Values.maptilerServer.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "maptiler-server.fullname" . }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
