{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "maptiler-server.fullname" . }}
  labels:
    {{- include "maptiler-server.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "maptiler-server.fullname" . }}
  minReplicas: {{ if .Values.maptilerServer.withAdmin }} {{ sub .Values.autoscaling.minReplicas 1 }} {{ else }} {{ .Values.autoscaling.minReplicas }} {{ end }}
  maxReplicas: {{ if .Values.maptilerServer.withAdmin }} {{ sub .Values.autoscaling.maxReplicas 1 }} {{ else }} {{ .Values.autoscaling.maxReplicas }} {{ end }}
  metrics:
    {{- if .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
